use crate::modules::overseer::handler::{
    installer::ModuleInstaller,
    InstallSource,
};

impl ModuleInstaller {
    pub async fn install_module(
        &self,
        source: InstallSource,
        custom_name: Option<String>,
    ) -> color_eyre::Result<String> {
        match source {
            InstallSource::Registry(module_id) => {
                self.install_from_registry(&module_id, custom_name).await
            }
            InstallSource::LocalFile(path) => self.install_from_file(&path, custom_name).await,
            InstallSource::DiscoveredDevice(mac) => Err(color_eyre::eyre::eyre!(
                "Device modules are auto-generated by DiscoveryManager"
            )),
        }
    }
}
